# Generated by Django 4.2.4 on 2023-09-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=110)),
                ('lname', models.CharField(max_length=110)),
                ('email', models.CharField(max_length=110)),
                ('area', models.CharField(max_length=110)),
            ],
        ),
    ]
